import assert from "node:assert/strict";
import { mkdirSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { codexArgs, codexEnv, defaultSandbox, main, parseRoleToml, type RolePins } from "../codexRole.ts";
import { withCapturedConsole } from "./helpers/captureConsole.ts";
import { withTmpDir } from "./helpers/tmpDir.ts";

function roleToml(overrides: Partial<Record<string, string | number>> = {}): string {
  const values = {
    model: "gpt-5.6-terra",
    model_reasoning_effort: "high",
    developer_instructions: "Follow the role contract.",
    ...overrides,
  };
  return [
    "# Generated by `pnpm agent-surface:sync`; edit the canonical prompt under `.agents/agents`.",
    ...Object.entries(values).map(([key, value]) => `${key} = ${JSON.stringify(value)}`),
    "",
  ].join("\n");
}

function roleArgs(tree: string, dispatch: string, out: string): string[] {
  return ["test-author", "--tree", tree, "--dispatch", dispatch, "--out", out];
}

test("a generated Codex role TOML preserves all three pins", () => {
  assert.deepEqual(parseRoleToml(roleToml()), {
    model: "gpt-5.6-terra",
    effort: "high",
    instructions: "Follow the role contract.",
    projectDocs: true,
    sandbox: null,
  });
});

test("the role's own sandbox wins over the default: toml sandbox_mode, then the agents.json row, then defaultSandbox", () => {
  withTmpDir("codex-role-", (dir) => {
    const dispatch = join(dir, "dispatch.md");
    const out = join(dir, "result.md");
    writeFileSync(dispatch, "Read this diff.\n");
    const sandboxOf = (role: string, deps: { readRole?: () => string | null; repoRole?: () => RolePins | null }) => {
      let args: string[] = [];
      const status = withCapturedConsole(() =>
        main([role, "--tree", dir, "--dispatch", dispatch, "--out", out], {
          ...deps,
          spawn: (_cmd, received) => {
            args = received;
            return 0;
          },
        })
      );
      assert.equal(status, 0);
      return args[args.indexOf("-s") + 1];
    };
    const repoPins = (sandbox: RolePins["sandbox"]): RolePins => ({ ...parseRoleToml(roleToml()), sandbox });
    // defaultSandbox("test-author") is workspace-write; each pin below says otherwise and wins.
    assert.equal(sandboxOf("test-author", { readRole: () => roleToml({ sandbox_mode: "read-only" }) }), "read-only");
    assert.equal(sandboxOf("review-cursory", { readRole: () => roleToml({ sandbox_mode: "workspace-write" }) }), "workspace-write");
    assert.equal(sandboxOf("test-author", { readRole: () => null, repoRole: () => repoPins("read-only") }), "read-only");
    // Named nowhere: the default.
    assert.equal(sandboxOf("test-author", { readRole: () => roleToml() }), "workspace-write");
    assert.equal(sandboxOf("review-cursory", { readRole: () => null, repoRole: () => repoPins(null) }), "read-only");
  });
});

test("a sandbox other than read-only or workspace-write is refused, never passed to Codex", () => {
  assert.throws(
    () => parseRoleToml(roleToml({ sandbox_mode: "danger-full-access" })),
    /codexRole: sandbox_mode in role toml must be read-only or workspace-write, got "danger-full-access"/
  );
});

test("a brief-only role TOML pins project_doc_max_bytes = 0, and the run passes it to Codex", () => {
  const pins = parseRoleToml(roleToml({ project_doc_max_bytes: 0 }));
  assert.equal(pins.projectDocs, false);
  const args = codexArgs({
    tree: "/tmp/readers-tree",
    sandbox: "read-only",
    model: "gpt-5.6-terra",
    effort: "high",
    out: "/tmp/result.md",
    projectDocs: false,
  });
  assert.deepEqual(args.slice(5, 9), ["-c", "project_doc_max_bytes=0", "-c", "approval_policy=never"]);
});

test("a generated Codex role TOML missing a pin identifies that key", () => {
  const incomplete = [
    "# Generated by `pnpm agent-surface:sync`; edit the canonical prompt under `.agents/agents`.",
    `model = ${JSON.stringify("gpt-5.6-terra")}`,
    `model_reasoning_effort = ${JSON.stringify("high")}`,
    "",
  ].join("\n");
  assert.throws(
    () => parseRoleToml(incomplete),
    /codexRole: developer_instructions missing in role toml/
  );
});

test("a writer can edit its isolated worktree while a cursory reader cannot", () => {
  assert.equal(defaultSandbox("test-author"), "workspace-write");
  assert.equal(defaultSandbox("review-cursory"), "read-only");
});

test("the Codex process receives the pinned exec argv in its required order", () => {
  assert.deepEqual(
    codexArgs({
      tree: "/tmp/writers-tree",
      sandbox: "workspace-write",
      model: "gpt-5.6-terra",
      effort: "high",
      out: "/tmp/result.md",
      projectDocs: true,
    }),
    [
      "exec",
      "-C",
      "/tmp/writers-tree",
      "-s",
      "workspace-write",
      "-c",
      "sandbox_workspace_write.network_access=true",
      "-c",
      "approval_policy=never",
      "-m",
      "gpt-5.6-terra",
      "-c",
      "model_reasoning_effort=high",
      "--skip-git-repo-check",
      "-o",
      "/tmp/result.md",
      "-",
    ]
  );
});

test("a role run forwards the canonical prompt, dispatch, and non-zero Codex result", () => {
  withTmpDir("codex-role-", (dir) => {
    const dispatch = join(dir, "dispatch.md");
    const out = join(dir, "result.md");
    writeFileSync(dispatch, "AUTHOR phase: own only this test file.\n");
    const calls: Array<{ cmd: string; args: string[]; input: string; log: string | null }> = [];
    const status = withCapturedConsole(() =>
      main(roleArgs(dir, dispatch, out), {
        readRole: () => roleToml(),
        spawn: (cmd, args, input, log) => {
          calls.push({ cmd, args, input, log });
          return 19;
        },
      })
    );
    assert.equal(status, 19);
    assert.deepEqual(calls, [
      {
        cmd: "codex",
        args: codexArgs({
          tree: dir,
          sandbox: "workspace-write",
          model: "gpt-5.6-terra",
          effort: "high",
          out,
          projectDocs: true,
        }),
        input: "Follow the role contract.\n\n---\n\nAUTHOR phase: own only this test file.\n",
        log: null,
      },
    ]);
  });
});

test("a paired cursory read is read-only and preserves its log destination", () => {
  withTmpDir("codex-role-", (dir) => {
    const dispatch = join(dir, "dispatch.md");
    const out = join(dir, "result.md");
    const log = join(dir, "codex.log");
    writeFileSync(dispatch, "Read this diff.\n");
    let call: { args: string[]; log: string | null } | undefined;
    const status = withCapturedConsole(() =>
      main(["review-cursory", "--tree", dir, "--dispatch", dispatch, "--out", out, "--log", log], {
        readRole: () => roleToml(),
        spawn: (_cmd, args, _input, receivedLog) => {
          call = { args, log: receivedLog };
          return 0;
        },
      })
    );
    assert.equal(status, 0);
    assert.deepEqual(call, {
      args: codexArgs({
        tree: dir,
        sandbox: "read-only",
        model: "gpt-5.6-terra",
        effort: "high",
        out,
        projectDocs: true,
      }),
      log,
    });
  });
});

test("invalid role invocations return one diagnostic line and status 2", () => {
  withTmpDir("codex-role-", (dir) => {
    const dispatch = join(dir, "dispatch.md");
    const out = join(dir, "result.md");
    writeFileSync(dispatch, "Read this diff.\n");
    const cases: Array<{
      name: string;
      argv: string[];
      readRole?: () => string | null;
      repoRole?: () => null;
      message: RegExp;
    }> = [
      {
        name: "unknown role",
        argv: roleArgs(dir, dispatch, out),
        readRole: () => null,
        repoRole: () => null,
        message: /unknown role|role.*not found/i,
      },
      {
        name: "missing tree",
        argv: ["test-author", "--dispatch", dispatch, "--out", out],
        message: /--tree/,
      },
      {
        name: "missing dispatch",
        argv: ["test-author", "--tree", dir, "--out", out],
        message: /--dispatch/,
      },
      {
        name: "missing out",
        argv: ["test-author", "--tree", dir, "--dispatch", dispatch],
        message: /--out/,
      },
      {
        name: "relative tree",
        argv: roleArgs("relative-tree", dispatch, out),
        message: /--tree.*absolute|absolute.*--tree/i,
      },
      {
        name: "missing output directory",
        argv: roleArgs(dir, dispatch, join(dir, "absent", "result.md")),
        message: /--out.*directory|directory.*--out/i,
      },
      {
        name: "dispatch file does not exist",
        argv: roleArgs(dir, join(dir, "absent-dispatch.md"), out),
        message: /--dispatch does not exist/,
      },
      {
        name: "missing log directory",
        argv: [...roleArgs(dir, dispatch, out), "--log", join(dir, "absent", "run.log")],
        message: /--log.*directory|directory.*--log/i,
      },
    ];
    for (const invalid of cases) {
      withCapturedConsole((captured) => {
        const status = main(invalid.argv, {
          readRole: invalid.readRole ?? (() => roleToml()),
          ...(invalid.repoRole ? { repoRole: invalid.repoRole } : {}),
        });
        assert.equal(status, 2, invalid.name);
        assert.equal(captured.errors.length, 1, `${invalid.name}: ${captured.errors.join("\n")}`);
        assert.match(captured.errors[0]!, invalid.message);
        assert.ok(
          !captured.errors[0]!.includes("\n"),
          `${invalid.name}: diagnostic spans two lines`
        );
      });
    }
  });
});

/** Runs `fn` with `process.env.PATH` set to an empty folder in `dir`, so no `codex` resolves. */
function withoutCodex<T>(dir: string, fn: () => T): T {
  const saved = process.env.PATH;
  const empty = join(dir, "empty-bin");
  mkdirSync(empty, { recursive: true });
  process.env.PATH = empty;
  try {
    return fn();
  } finally {
    process.env.PATH = saved;
  }
}

test("a codex binary missing from PATH is exit 2 with one line naming PATH, with or without a log", () => {
  withTmpDir("codex-role-", (dir) => {
    const dispatch = join(dir, "dispatch.md");
    writeFileSync(dispatch, "Read this diff.\n");
    for (const log of [[], ["--log", join(dir, "codex.log")]]) {
      withCapturedConsole((captured) => {
        const status = withoutCodex(dir, () =>
          main([...roleArgs(dir, dispatch, join(dir, "result.md")), ...log], { readRole: () => roleToml() })
        );
        assert.equal(status, 2, log.join(" "));
        assert.deepEqual(captured.errors, ["codexRole: codex is not on PATH — install Codex or map a codex_role step"]);
      });
    }
  });
});

test("a log that cannot be opened keeps its own ENOENT and path, never the not-on-PATH message", () => {
  withTmpDir("codex-role-", (dir) => {
    const dispatch = join(dir, "dispatch.md");
    writeFileSync(dispatch, "Read this diff.\n");
    // The log's folder exists, so the argv check passes; the link aims into a folder that does not.
    const log = join(dir, "codex.log");
    symlinkSync(join(dir, "gone", "codex.log"), log);
    withCapturedConsole((captured) => {
      assert.throws(
        () =>
          withoutCodex(dir, () =>
            main([...roleArgs(dir, dispatch, join(dir, "result.md")), "--log", log], { readRole: () => roleToml() })
          ),
        (e: NodeJS.ErrnoException) => e.code === "ENOENT" && e.syscall === "open" && e.path === log
      );
      assert.deepEqual(captured.errors, []);
    });
  });
});

test("an unknown flag becomes a usage exit with the shared strict-argv diagnostic", () => {
  withTmpDir("codex-role-", (dir) => {
    const dispatch = join(dir, "dispatch.md");
    const out = join(dir, "result.md");
    writeFileSync(dispatch, "Read this diff.\n");
    withCapturedConsole((captured) => {
      const status = main([...roleArgs(dir, dispatch, out), "--sandbox"], {
        readRole: () => roleToml(),
      });
      assert.equal(status, 2);
      assert.equal(captured.errors.length, 1);
      assert.match(captured.errors[0]!, /unknown flag\(s\): --sandbox — known:/);
    });
  });
});

test("every Codex run gets DO_NOT_TRACK=1 and keeps the caller's env", () => {
  assert.deepEqual(codexEnv({ PATH: "/bin", HOME: "/h" }), { PATH: "/bin", HOME: "/h", DO_NOT_TRACK: "1" });
});
